// @generated by apps/ui/scripts/build-registry.ts — DO NOT EDIT.
import * as React from "react";

export const Index: Record<string, { name: string; description?: string; component: React.LazyExoticComponent<React.ComponentType> }> = {
  "p-fugue-auth-form": {
    name: "p-fugue-auth-form",
    description: "Accessible Fugue auth form composition with safe example data.",
    component: React.lazy(() => import("@/registry/default/particles/p-fugue-auth-form")),
  },
  "p-fugue-console-shell": {
    name: "p-fugue-console-shell",
    description: "Fugue console shell composition with sidebar and resource status.",
    component: React.lazy(() => import("@/registry/default/particles/p-fugue-console-shell")),
  },
  "p-fugue-resource-table": {
    name: "p-fugue-resource-table",
    description: "Dense, labelled resource table with status and row action.",
    component: React.lazy(() => import("@/registry/default/particles/p-fugue-resource-table")),
  },
  "p-fugue-environment-editor": {
    name: "p-fugue-environment-editor",
    description: "Environment variable editor using Field and InputGroup contracts.",
    component: React.lazy(() => import("@/registry/default/particles/p-fugue-environment-editor")),
  },
};
