'use client';
import { useCallback, useEffect, useState } from 'react';
import type { ObjectStore, ObjectStorageCredential } from '@/lib/fugue/console';
import { useI18n } from '@/lib/i18n/client';
import { fmtBytes } from '@/lib/format';
import './storage.css';

type Choice = {id:string;name:string;project_id?:string};
type Inventory = {stores:ObjectStore[];projects:Choice[];apps:Choice[]};
async function api<T>(url:string,body?:unknown):Promise<T>{const res=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);return data.result;}
export default function StorageManager(){
 const {t}=useI18n();const [data,setData]=useState<Inventory>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [project,setProject]=useState('');const [selected,setSelected]=useState('');const [creds,setCreds]=useState<ObjectStorageCredential[]>([]);const [name,setName]=useState('');const [app,setApp]=useState('');const [grantName,setGrantName]=useState('');const [permission,setPermission]=useState('read-only');const [notice,setNotice]=useState('');
 const reload=useCallback(async()=>{const inv=await api<Inventory>('/api/console/storage');setData(inv);setProject(p=>p||inv.projects[0]?.id||'');},[]);
 useEffect(()=>{reload().catch(e=>setError(e.message));},[reload]);
 useEffect(()=>{let current=true;setCreds([]);if(selected)api<{credentials:ObjectStorageCredential[]}>(`/api/console/storage?id=${encodeURIComponent(selected)}`).then(d=>{if(current)setCreds(d.credentials)}).catch(e=>{if(current)setError(e.message)});return()=>{current=false}},[selected,data]);
 async function mutate(body:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{await api('/api/console/storage',body);await reload();setNotice(t('Storage updated.'));}catch(e){setError(e instanceof Error?e.message:t('Request failed'));}finally{setBusy(false)}}
 const current=data?.stores.find(s=>s.id===selected);
 return <div className="page storage-page"><div className="phead"><div><div className="eyebrow">S3 COMPATIBLE</div><h1>{t('Object storage')}</h1><p className="muted">{t('Private buckets for your projects. Data survives application releases.')}</p></div><button className="btn" disabled={busy} onClick={()=>reload().catch(e=>setError(e.message))}>{t('Refresh')}</button></div>
 {error&&<div role="alert" className="storage-alert">{error}</div>}{notice&&<p role="status">{notice}</p>}
 <form className="panel storage-create" onSubmit={e=>{e.preventDefault();void mutate({action:'create',project_id:project,name})}}><label>{t('Project')}<select value={project} onChange={e=>setProject(e.target.value)} required>{data?.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{t('Bucket name')}<input value={name} onChange={e=>setName(e.target.value)} pattern="[a-z0-9][a-z0-9-]{0,47}" placeholder="request-facts" required/></label><button className="btn primary" disabled={busy||!project}>{t('Create private bucket')}</button><p className="muted">{t('Storage is optional. Access is disabled until you issue an application credential.')}</p></form>
 {!data?<div className="panel empty">{t('Loading…')}</div>:data.stores.length===0?<div className="panel empty">{t('No object storage enabled yet.')}</div>:<div className="storage-grid">{data.stores.map(s=><button key={s.id} className={`panel storage-card ${selected===s.id?'selected':''}`} onClick={()=>{setSelected(s.id);setApp('')}}><div><strong>{s.name}</strong><span className={`chip ${s.status==='active'?'ok':'idle'}`}>{s.status}</span></div><p className="muted">{data.projects.find(p=>p.id===s.project_id)?.name||s.project_id}</p><strong>{s.usage_measured_at?fmtBytes(s.used_bytes):t('Not measured')}</strong><small>{s.usage_measured_at?`${s.object_count} objects · ${new Date(s.usage_measured_at).toLocaleString()}`:t('Measure usage to see stored bytes.')}</small></button>)}</div>}
 {current&&<section className="panel storage-detail"><div className="storage-detail-head"><h2>{current.name}</h2><button className="btn" disabled={busy} onClick={()=>void mutate({action:'measure',id:current.id})}>{t('Measure usage')}</button><button className="btn" disabled={busy} onClick={()=>{if(current.status==='disabled'||window.confirm(t('Revoke all bucket credentials? Objects will be retained.')))void mutate({action:'update',id:current.id,enabled:current.status==='disabled'})}}>{current.status==='disabled'?t('Enable'):t('Disable access')}</button></div><dl><dt>Endpoint</dt><dd>{current.endpoint}</dd><dt>Bucket</dt><dd>{current.bucket}</dd><dt>{t('Storage budget')}</dt><dd>{current.quota_bytes?fmtBytes(current.quota_bytes):t('Not set')} · {t('Soft budget')}</dd></dl>
 <h3>{t('Application credentials')}</h3><p className="muted">{t('Each credential grants access to this bucket only. Binding writes S3 environment variables to the selected app.')}</p>
 <form className="storage-create" onSubmit={e=>{e.preventDefault();void mutate({action:'bind',id:current.id,app_id:app,name:grantName,permission})}}><label>{t('Application')}<select value={app} onChange={e=>setApp(e.target.value)} required><option value="">{t('Select application')}</option>{data?.apps.map(a=><option key={a.id} value={a.id}>{a.name}{a.project_id!==current.project_id?' · '+(data.projects.find(p=>p.id===a.project_id)?.name||''):''}</option>)}</select></label><label>{t('Credential name')}<input value={grantName} onChange={e=>setGrantName(e.target.value)} pattern="[a-z0-9][a-z0-9-]{0,47}" required placeholder="analytics-reader"/></label><label>{t('Permission')}<select value={permission} onChange={e=>setPermission(e.target.value)}><option value="read-only">{t('Read only')}</option><option value="read-write">{t('Read and write')}</option></select></label><button className="btn primary" disabled={busy||current.status!=='active'}>{t('Bind to application')}</button></form>
 <div className="storage-credentials">{creds.map(c=><div key={c.id}><span><strong>{c.name}</strong><small>{data?.apps.find(a=>a.id===c.app_id)?.name||c.app_id} · {c.permission} · {c.status}</small></span><button className="btn" disabled={busy||c.status==='revoked'} onClick={()=>{if(window.confirm(t('Revoke this credential? The application will lose bucket access.')))void mutate({action:'revoke',id:current.id,credential_id:c.id})}}>{t('Revoke')}</button></div>)}{!creds.length&&<p className="muted">{t('No credentials issued.')}</p>}</div></section>}
 </div>
}
