import { execFileSync } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { registry } from "@/registry/index";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputRoot = path.join(appRoot, "public/r");

const fixedRegistry = {
  ...registry,
  items: registry.items.map((item) => ({
    ...item,
    files: item.files?.map((file) =>
      typeof file === "string"
        ? `registry/default/${file}`
        : { ...file, path: `registry/default/${file.path}` },
    ),
  })),
};

const particles = registry.items.filter((item) =>
  item.files?.some((file) => {
    const source = typeof file === "string" ? file : file.path;
    return source.startsWith("particles/");
  }),
);

const index = `// @generated by apps/ui/scripts/build-registry.ts — DO NOT EDIT.
import * as React from "react";

export const Index: Record<string, { name: string; description?: string; component: React.LazyExoticComponent<React.ComponentType> }> = {
${particles
  .map((item) => {
    const firstFile = item.files?.[0];
    const source = (
      typeof firstFile === "string" ? firstFile : firstFile?.path
    )?.replace(/\.tsx?$/, "");
    return `  ${JSON.stringify(item.name)}: {
    name: ${JSON.stringify(item.name)},
    description: ${JSON.stringify(item.description)},
    component: React.lazy(() => import(${JSON.stringify(`@/registry/default/${source}`)})),
  },`;
  })
  .join("\n")}
};
`;

await fs.mkdir(path.join(appRoot, "registry"), { recursive: true });
// The shadcn builder overwrites current items but does not remove JSON emitted
// for deleted items. Recreate the generated directory so an old installable
// artifact can never outlive its registry source.
await fs.rm(outputRoot, { force: true, recursive: true });
await fs.mkdir(outputRoot, { recursive: true });
await fs.writeFile(
  path.join(appRoot, "registry.json"),
  `${JSON.stringify(fixedRegistry, null, 2)}\n`,
  "utf8",
);
await fs.writeFile(path.join(appRoot, "registry/__index__.tsx"), index, "utf8");

execFileSync(
  process.execPath,
  ["x", "--bun", "shadcn@4.1.0", "build", "registry.json", "--output", "public/r"],
  { cwd: appRoot, stdio: "inherit" },
);

const generatedFiles = (await fs.readdir(outputRoot)).filter((file) =>
  file.endsWith(".json"),
);
for (const file of generatedFiles) {
  const target = path.join(outputRoot, file);
  const item = JSON.parse(await fs.readFile(target, "utf8")) as {
    meta?: Record<string, unknown>;
  };
  item.meta = {
    ...item.meta,
    generated: true,
    source: "apps/ui/registry/default",
    warning: "DO NOT EDIT: regenerate with bun run registry:build",
  };
  await fs.writeFile(target, `${JSON.stringify(item, null, 2)}\n`, "utf8");
}

await fs.writeFile(
  path.join(outputRoot, "README.md"),
  "# Generated registry output\n\nDO NOT EDIT files in this directory. Run `bun run registry:build` from `apps/ui`.\n",
  "utf8",
);

console.log(
  `Built ${generatedFiles.length} registry JSON files and ${particles.length} lazy particle entries.`,
);
