"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { ProjectTemplate } from "@/lib/templates/store";

export default function TemplateDeploy({ token, template }: { token: string; template: ProjectTemplate }) {
  const router = useRouter(); const [name, setName] = useState(`${template.name} copy`); const [env, setEnv] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const envKeys = [...new Set(template.apps.flatMap((app) => app.envKeys ?? []))];
  async function deploy() { setBusy(true); setError(null); try { const res = await fetch(`/api/templates/${encodeURIComponent(token)}/deploy`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectName: name, env }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Deployment failed"); const id = data.result?.projectId; router.push(id ? `/projects/${encodeURIComponent(id)}` : "/projects"); } catch (e) { setError(e instanceof Error ? e.message : "Deployment failed"); setBusy(false); } }
  return <div className="template-deploy"><div className="panel"><div className="panel-h"><h3>Included apps</h3></div><div className="form">{template.apps.map((app) => <div className="form-row" key={app.name}><label>{app.name}</label><span className="mono">{app.source.type === "image" ? app.source.imageRef : app.source.repoUrl}</span></div>)}</div></div><div className="panel"><div className="panel-h"><h3>Deploy this template</h3></div><div className="form"><div className="form-row"><label>Project name</label><input className="input" value={name} onChange={(e) => setName(e.target.value)} /></div>{envKeys.map((key) => <div className="form-row" key={key}><label>{key}</label><input className="input mono" type="password" value={env[key] ?? ""} onChange={(e) => setEnv((current) => ({ ...current, [key]: e.target.value }))} placeholder="Required secret" /></div>)}<p className="form-hint">Secrets and account-specific settings are not included. Values are sent only to your deployment.</p></div>{error && <div className="error">{error}</div>}<div className="form-foot"><button className="btn primary" disabled={busy || !name.trim()} onClick={deploy}>{busy ? "Deploying…" : "Deploy template"}</button></div></div></div>;
}
